"use client";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { GeneralProvider } from "@/core/providers/general-provider";
import BackgroundCircles from "@/shared/components/layout/background-circles";
import { usePathname } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Since this is a client component now, we can't export metadata directly.
// This should be moved to a parent server component or handled in page.tsx if needed.
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const showBackground = pathname === "/login";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {showBackground && <BackgroundCircles />}
        <GeneralProvider>{children}</GeneralProvider>
      </body>
    </html>
  );
}
