"use client";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { GeneralProvider } from "@/core/providers/general-provider";
import BackgroundCircles from "@/shared/components/layout/background-circles";
import { usePathname } from "next/navigation";
import { MobileNavBar } from "@/shared/components/layout/mobile-nav-bar";
import { cn } from "@/lib/utils";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Since this is a client component now, we can't export metadata directly.
// This should be moved to a parent server component or handled in page.tsx if needed.
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const showBackground = pathname === "/login";
  const showMobileNav = ["/qr-code", "/route-sheets"].includes(pathname);

  return (
    <html lang="en">
      <body
        className={cn(
          `${geistSans.variable} ${geistMono.variable} antialiased`,
          // Add padding-bottom on mobile to avoid content being hidden by the nav bar
          { "pb-16 sm:pb-0": showMobileNav }
        )}
      >
        {showBackground && <BackgroundCircles />}
        <GeneralProvider>{children}</GeneralProvider>
        {showMobileNav && <MobileNavBar />}
      </body>
    </html>
  );
}
